import { PageHeading } from "@/components/page-heading";
import { UploadPdfForm } from "@/components/imports/upload-pdf-form";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/utils";

const status:Record<string,{label:string,style:string}>={UPLOADED:{label:"已上传",style:"bg-slate-100 text-slate-700"},PENDING_OCR:{label:"等待 OCR",style:"bg-amber-50 text-amber-700"},PENDING_PARSE:{label:"等待结构化",style:"bg-blue-50 text-blue-700"},PENDING_REVIEW:{label:"待人工校对",style:"bg-purple-50 text-purple-700"},COMPLETED:{label:"已完成",style:"bg-emerald-50 text-emerald-700"},FAILED:{label:"处理失败",style:"bg-red-50 text-red-700"}};
export const metadata={title:"PDF 导入"};
export default async function ImportsPage(){ const user=await requireAdmin(); const imports=await db.pdfImport.findMany({where:{importedById:user.id},orderBy:{createdAt:"desc"},take:50}); return <><PageHeading title="PDF 导入" description="上传后先识别和结构化，再由管理员逐题校对发布。"/><div className="grid gap-6 xl:grid-cols-[420px_1fr]"><div><UploadPdfForm/><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>当前三份真题说明：</strong>正文为图片截图，普通文本解析无法读取，系统会自动进入中文 OCR 队列，不会直接发布。</div></div><section className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">导入记录</h2><p className="mt-1 text-sm text-slate-500">可查看文件检查结果和校对进度</p></div><div className="divide-y divide-slate-100">{imports.map(item=>{const s=status[item.status]??status.UPLOADED;return <article key={item.id} className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div className="min-w-0"><p className="truncate font-medium text-slate-800">{item.originalFilename}</p><p className="mt-1 text-sm text-slate-500">{item.pageCount??"—"} 页 · {formatDate(item.createdAt)}</p></div><span className={`h-fit w-fit rounded-full px-3 py-1 text-xs font-medium ${s.style}`}>{s.label}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#b4232d]" style={{width:item.totalQuestions?`${Math.round(item.reviewedQuestions/item.totalQuestions*100)}%`:"4%"}}/></div><p className="mt-2 text-xs text-slate-500">已校对 {item.reviewedQuestions} / {item.totalQuestions} 题</p></article>})}{imports.length===0&&<div className="p-12 text-center text-sm text-slate-500">还没有导入记录。</div>}</div></section></div></>; }
