import Link from "next/link";
import { Pencil, Plus, Search } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { DeleteQuestion } from "@/components/questions/delete-question";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
const typeName:Record<string,string>={SINGLE_CHOICE:"单选",MULTIPLE_CHOICE:"多选",TRUE_FALSE:"判断",SHORT_ANSWER:"简答",MATERIAL_ANALYSIS:"材料分析"};
export const metadata={title:"题库管理"};
export default async function QuestionsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){ const user=await requireUser(); const p=await searchParams; const q=p.q?.trim()??""; const type=p.type??""; const questions=await db.question.findMany({where:{deletedAt:null,isActive:true,...(type?{type}:{}),...(q?{OR:[{stem:{contains:q,mode:"insensitive"}},{chapter:{contains:q,mode:"insensitive"}},{knowledgePoint:{contains:q,mode:"insensitive"}}]}:{})},orderBy:{createdAt:"desc"},take:100}); return <><PageHeading title="题库管理" description="筛选、校对和维护所有正式题目。" action={user.role==="ADMIN"?<Link href="/questions/new" className="btn-primary"><Plus size={18}/>新增题目</Link>:undefined}/><form className="card mb-5 grid gap-3 p-4 sm:grid-cols-[1fr_180px_auto]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input name="q" defaultValue={q} className="field pl-10" placeholder="搜索题干、章节或知识点"/></label><select name="type" defaultValue={type} className="field"><option value="">全部题型</option>{Object.entries(typeName).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="btn-secondary">筛选</button></form><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3 font-medium">题目</th><th className="px-4 py-3 font-medium">题型</th><th className="px-4 py-3 font-medium">章节</th><th className="px-4 py-3 font-medium">难度</th><th className="px-4 py-3 font-medium">状态</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{questions.map(item=><tr key={item.id} className="hover:bg-slate-50/70"><td className="max-w-xl px-5 py-4"><p className="line-clamp-2 font-medium leading-6 text-slate-800">{item.stem}</p><p className="mt-1 text-xs text-slate-400">{item.sourcePdf||"手动录入"}</p></td><td className="px-4 py-4">{typeName[item.type]||item.type}</td><td className="px-4 py-4 text-slate-600">{item.chapter||"—"}</td><td className="px-4 py-4">{item.difficulty}</td><td className="px-4 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{item.reviewStatus}</span></td><td className="px-4 py-4"><div className="flex justify-end">{user.role==="ADMIN"&&<><Link className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-800" href={`/questions/${item.id}`}><Pencil size={17}/></Link><DeleteQuestion id={item.id}/></>}</div></td></tr>)}{questions.length===0&&<tr><td colSpan={6} className="p-12 text-center text-slate-500">没有符合条件的题目。</td></tr>}</tbody></table></div></div></>; }
